---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## 3. Sampling with replacement

The function choose lets us compute posisble subsets from a sample space of defined size.
Use choose(x, y) where x = size of set, and y = the number of objects chosen
Returns the number of possible sequences of choices, replacing the balls each time

```{r}
choose(8,3)
```


$$ P(A_{35,z}) = \binom{35}{z} \cdot (\frac{3}{10})^z \cdot (1-(\frac{3}{10}))^{35-z}  $$
$$ P(A_{35,z}) =  \frac{35!}{z!(35-z)!} \cdot (\frac{3}{10})^z \cdot (\frac{7}{10})^{35-z} $$
Define a function that does the above
```{r}

prob_red_spheres <- function(z) {
  a <- factorial(35) / (factorial(z) * factorial (35-z))
  b <- 0.3**z
  c <- 0.7**(35-z)
  return(a*b*c)
}

prob_red_spheres(12)
```

Generate Dataframe

```{r}
reds <- seq(1, 35)
prob <- vector()

for (i in reds) {
  prob <- c(prob, prob_red_spheres(i))
}

probByNumReds = data.frame(reds, prob)
head(probByNumReds)

```


```{r}
probByNumReds %>% 
  ggplot(aes(x=reds, y=prob)) + geom_line(
```

```{r}
set.seed(0)
for (i in seq(1, 5)) {
print(sample(10,35,replace=TRUE))
}
```

Cheating with r

```{r}
trials <- 1000
set.seed(0)

samplingWithReplacementSim <- data.frame(trial=1:trials) %>% 
  mutate(sample_balls=map(.x=trial, ~sample(10, 35, replace=TRUE))) %>% 
  mutate(num_reds=map(.x=sample_balls, function(x) {return(sum(x < 3))} ))


samplingWithReplacementSim$sample_balls[1]
```






















